package com.shraggen.diarium

import com.shraggen.diarium.speech.SpeechLanguage

internal data class AppCopy(
    val title: String,
    val language: String,
    val llmMissing: String,
    val whisperMissing: String,
    val ready: String,
    val selectLlm: String,
    val changeLlm: String,
    val selectWhisper: String,
    val changeWhisper: String,
    val command: String,
    val commandPlaceholder: String,
    val process: String,
    val recordVoice: String,
    val stopRecording: String,
    val listening: String,
    val transcribing: String,
    val detectedLanguage: String,
    val result: String,
    val confirmWrite: String,
    val tool: String,
    val nothingSaved: String,
    val confirm: String,
    val cancel: String,
    val journal: String,
    val emptyJournal: String,
    val hive: String,
    val queenSeen: String,
    val queenNotSeen: String,
    val record: String,
)

internal fun copyFor(language: SpeechLanguage): AppCopy =
    when (language) {
        SpeechLanguage.ENGLISH -> ENGLISH_COPY
        SpeechLanguage.GERMAN -> GERMAN_COPY
        SpeechLanguage.SERBIAN -> SERBIAN_COPY
    }

private val ENGLISH_COPY = AppCopy(
    title = "Diarium local inspection journal",
    language = "Language",
    llmMissing = "Select an instruction-tuned GGUF model to begin.",
    whisperMissing = "Select a multilingual Whisper .bin model for voice input.",
    ready = "Ready",
    selectLlm = "Select GGUF model",
    changeLlm = "Change GGUF model",
    selectWhisper = "Select Whisper model",
    changeWhisper = "Change Whisper model",
    command = "Command",
    commandPlaceholder = "I inspected hive 4 and saw the queen.",
    process = "Process locally",
    recordVoice = "Record voice",
    stopRecording = "Stop recording",
    listening = "Listening… Silero will stop after you finish speaking.",
    transcribing = "Transcribing locally with Whisper…",
    detectedLanguage = "Whisper language",
    result = "Result",
    confirmWrite = "Confirm journal write",
    tool = "Tool",
    nothingSaved = "Nothing is saved until you confirm.",
    confirm = "Confirm",
    cancel = "Cancel",
    journal = "Inspection journal",
    emptyJournal = "No inspections recorded yet.",
    hive = "Hive",
    queenSeen = "Queen seen",
    queenNotSeen = "Queen not seen",
    record = "Record",
)

private val GERMAN_COPY = AppCopy(
    title = "Lokales Diarium-Inspektionsjournal",
    language = "Sprache",
    llmMissing = "Wähle ein instruktionsoptimiertes GGUF-Modell aus.",
    whisperMissing = "Wähle ein mehrsprachiges Whisper-.bin-Modell für Spracheingaben aus.",
    ready = "Bereit",
    selectLlm = "GGUF-Modell auswählen",
    changeLlm = "GGUF-Modell wechseln",
    selectWhisper = "Whisper-Modell auswählen",
    changeWhisper = "Whisper-Modell wechseln",
    command = "Befehl",
    commandPlaceholder = "Ich habe Bienenstock 4 kontrolliert und die Königin gesehen.",
    process = "Lokal verarbeiten",
    recordVoice = "Sprache aufnehmen",
    stopRecording = "Aufnahme beenden",
    listening = "Aufnahme läuft… Silero stoppt, sobald du fertig gesprochen hast.",
    transcribing = "Whisper transkribiert lokal…",
    detectedLanguage = "Whisper-Sprache",
    result = "Ergebnis",
    confirmWrite = "Journaleintrag bestätigen",
    tool = "Werkzeug",
    nothingSaved = "Bis zur Bestätigung wird nichts gespeichert.",
    confirm = "Bestätigen",
    cancel = "Abbrechen",
    journal = "Inspektionsjournal",
    emptyJournal = "Noch keine Inspektionen erfasst.",
    hive = "Bienenstock",
    queenSeen = "Königin gesehen",
    queenNotSeen = "Königin nicht gesehen",
    record = "Eintrag",
)

private val SERBIAN_COPY = AppCopy(
    title = "Локални дневник прегледа",
    language = "Језик",
    llmMissing = "Изаберите инструкцијски подешен GGUF модел.",
    whisperMissing = "Изаберите вишејезични Whisper .bin модел за гласовни унос.",
    ready = "Спремно",
    selectLlm = "Изабери GGUF модел",
    changeLlm = "Промени GGUF модел",
    selectWhisper = "Изабери Whisper модел",
    changeWhisper = "Промени Whisper модел",
    command = "Наредба",
    commandPlaceholder = "Прегледао сам кошницу 4 и видео матицу.",
    process = "Обради локално",
    recordVoice = "Сними глас",
    stopRecording = "Заустави снимање",
    listening = "Слушам… Silero ће стати када завршите.",
    transcribing = "Whisper локално транскрибује…",
    detectedLanguage = "Whisper језик",
    result = "Резултат",
    confirmWrite = "Потврди упис у дневник",
    tool = "Алат",
    nothingSaved = "Ништа се не чува док не потврдите.",
    confirm = "Потврди",
    cancel = "Откажи",
    journal = "Дневник прегледа",
    emptyJournal = "Још нема сачуваних прегледа.",
    hive = "Кошница",
    queenSeen = "Матица виђена",
    queenNotSeen = "Матица није виђена",
    record = "Запис",
)
